# Generated by Django 5.0.8 on 2026-06-17 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('category', models.CharField(blank=True, help_text='Internal, DIPA, BRIN, Industri, Internasional', max_length=80)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Tersedia'), ('BORROWED', 'Dipinjam'), ('MAINTENANCE', 'Perawatan'), ('RETIRED', 'Tidak Aktif')], default='AVAILABLE', max_length=30)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('partner_type', models.CharField(choices=[('INDUSTRY', 'Industri'), ('GOVERNMENT', 'Pemerintah'), ('UNIVERSITY', 'Perguruan Tinggi'), ('SCHOOL', 'Sekolah'), ('COMMUNITY', 'Komunitas'), ('ALUMNI', 'Alumni')], max_length=30)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('strategic_value', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityServiceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=260)),
                ('partner_name', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROPOSAL', 'Proposal'), ('ONGOING', 'Berjalan'), ('COMPLETED', 'Selesai'), ('CANCELLED', 'Dibatalkan')], default='DRAFT', max_length=30)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('output_summary', models.TextField(blank=True)),
                ('outcome_summary', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_service_projects', to='memberships.memberprofile')),
                ('members', models.ManyToManyField(blank=True, related_name='service_projects', to='memberships.memberprofile')),
                ('funding_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.fundingsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='enterprise.organizationunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollaborationAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('agreement_type', models.CharField(choices=[('MOU', 'MoU'), ('MOA', 'MoA'), ('IA', 'Implementation Arrangement'), ('NDA', 'NDA'), ('CONTRACT', 'Kontrak')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('ACTIVE', 'Aktif'), ('EXPIRED', 'Kedaluwarsa'), ('TERMINATED', 'Dihentikan')], default='DRAFT', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('document_url', models.URLField(blank=True)),
                ('scope', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.memberprofile')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='enterprise.partner')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=260)),
                ('abstract', models.TextField(blank=True)),
                ('scheme', models.CharField(choices=[('INTERNAL', 'Internal Universitas'), ('DIPA', 'DIPA/Unggulan'), ('NATIONAL', 'Nasional'), ('INDUSTRY', 'Industri'), ('INTERNATIONAL', 'Internasional'), ('INDEPENDENT', 'Mandiri')], default='INTERNAL', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROPOSAL', 'Proposal'), ('REVIEW', 'Review'), ('FUNDED', 'Didanai'), ('ONGOING', 'Berjalan'), ('COMPLETED', 'Selesai'), ('CANCELLED', 'Dibatalkan')], default='DRAFT', max_length=30)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('expected_outputs', models.TextField(blank=True)),
                ('risks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('funding_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.fundingsource')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_research_projects', to='memberships.memberprofile')),
                ('members', models.ManyToManyField(blank=True, related_name='research_projects', to='memberships.memberprofile')),
                ('research_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.researchgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('publication_type', models.CharField(choices=[('JOURNAL', 'Jurnal'), ('CONFERENCE', 'Konferensi'), ('BOOK', 'Buku/Bab Buku'), ('IPR', 'HKI/Paten'), ('OTHER', 'Lainnya')], default='JOURNAL', max_length=30)),
                ('indexing', models.CharField(choices=[('SCOPUS_Q1', 'Scopus Q1'), ('SCOPUS_Q2', 'Scopus Q2'), ('SCOPUS_Q3', 'Scopus Q3'), ('SCOPUS_Q4', 'Scopus Q4'), ('SINTA_1', 'SINTA 1'), ('SINTA_2', 'SINTA 2'), ('SINTA_3', 'SINTA 3'), ('NON_INDEXED', 'Non-indexed')], default='NON_INDEXED', max_length=30)),
                ('venue', models.CharField(blank=True, max_length=220)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=180)),
                ('url', models.URLField(blank=True)),
                ('citation_count', models.PositiveIntegerField(default=0)),
                ('authors', models.ManyToManyField(blank=True, related_name='publications', to='memberships.memberprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='enterprise.researchproject')),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('data_dictionary', models.TextField(blank=True)),
                ('access_level', models.CharField(default='Internal', max_length=60)),
                ('version', models.CharField(default='1.0.0', max_length=30)),
                ('repository_url', models.URLField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='memberships.memberprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='enterprise.researchproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_name', models.CharField(max_length=150)),
                ('purpose', models.CharField(max_length=240)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Diajukan'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('CANCELLED', 'Dibatalkan')], default='REQUESTED', max_length=30)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.memberprofile')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SourceCodeRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('url', models.URLField()),
                ('technology_stack', models.CharField(blank=True, max_length=250)),
                ('license', models.CharField(blank=True, max_length=80)),
                ('visibility', models.CharField(default='Private', max_length=40)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='enterprise.researchproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KPIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('RESEARCH', 'Penelitian'), ('PUBLICATION', 'Publikasi'), ('SERVICE', 'Pengabdian'), ('PARTNERSHIP', 'Kerja Sama'), ('TALENT', 'Talenta'), ('FINANCE', 'Keuangan')], max_length=30)),
                ('name', models.CharField(max_length=180)),
                ('year', models.PositiveIntegerField()),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.memberprofile')),
            ],
            options={
                'ordering': ['-year', 'category', 'name'],
                'unique_together': {('category', 'name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LabPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('responsibility', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='memberships.memberprofile')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.organizationunit')),
            ],
            options={
                'ordering': ['-start_date', 'title'],
                'indexes': [models.Index(fields=['title', 'is_active'], name='enterprise__title_573630_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['status', 'scheme'], name='enterprise__status_c64b21_idx'),
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['start_date'], name='enterprise__start_d_4c3acc_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['year', 'indexing'], name='enterprise__year_58c02c_idx'),
        ),
    ]
