# Generated by Django 5.0.8 on 2026-06-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_curriculumsupport_digitalchannel_headapproval_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalchannel',
            options={'ordering': ['channel_type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='roadmapitem',
            options={'ordering': ['start_year', 'priority', 'title']},
        ),
        migrations.AlterModelOptions(
            name='talentprogram',
            options={'ordering': ['-created_at', 'title']},
        ),
    ]
