# Generated by Django 5.0.8 on 2026-06-17 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('RESEARCH', 'Riset'), ('SERVICE', 'Pengabdian'), ('TRAINING', 'Pelatihan'), ('INTERNAL', 'Internal Lab'), ('INDUSTRY', 'Kolaborasi Industri')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, to='memberships.memberprofile')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['activity_type', 'start_date'], name='activities__activit_a4f1fc_idx')],
            },
        ),
    ]
