# Generated by Django 5.0.8 on 2026-06-17 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_type', models.CharField(choices=[('LECTURER', 'Dosen'), ('STUDENT', 'Mahasiswa'), ('ALUMNI', 'Alumni'), ('EXTERNAL', 'Eksternal')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Verifikasi'), ('ACTIVE', 'Aktif'), ('INACTIVE', 'Tidak Aktif'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=20)),
                ('expertise', models.CharField(blank=True, max_length=255)),
                ('generation', models.CharField(blank=True, help_text='Angkatan mahasiswa', max_length=20)),
                ('program_study', models.CharField(blank=True, max_length=120)),
                ('position', models.CharField(blank=True, help_text='Contoh: Kepala Lab, Asisten, Peneliti', max_length=120)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
                ('research_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.researchgroup')),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='memberships.memberprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['status', 'member_type'], name='memberships_status_fdb802_idx'),
        ),
    ]
